[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -nographic -bios none -machine virt -m 3G -smp 3 -kernel"
rustflags = [
  "-C",
  "link-arg=-Tlinker.ld",
]

[build]
target = "riscv64imac-unknown-none-elf"
